version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '4000:8080'
    volumes:
      - .docker/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    build:
      context: .
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - '9000:9000'
    volumes:
      - .docker/sonarqube_conf:/opt/sonarqube/conf
      - .docker/sonarqube_data:/opt/sonarqube/data
      - .docker/sonarqube_extensions:/opt/sonarqube/extensions
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - .docker/sonarqube_db:/var/lib/postgresql
      - .docker/postgresql_data:/var/lib/postgresql/data
